config/routes.rb
Rails.application.routes.draw do

  root 'home#show'

  get '/test' => 'test#show'
  get '/test/pollute' => 'test#pollute'
  get '/test/stream' => 'test#stream'
  get '/test/stream_json' => 'test#stream_json'

  get '/ts' => 'ts#hello'
  get '/test_ng2' => 'test_ng2#hello'

  resources :svelte_test, only: [] do
    collection do
      get :hello
      get :typeahead
      get :select
      post :select, as: :post_select
    end
  end

  resources :experiments, only: [] do
    collection do
      get :svelte_jumper
      get :cube3d
      get :learnopengl
    end
  end

  resources :search, only: [] do
    collection do
      post :search_xhr
    end
  end

  namespace :gi_paint do
    resources :ui, only: [] do
      collection do
        get '(*path)', to: 'ui#show', as: :ui
      end
    end

    root 'ui#show'
  end

  namespace :gi_raycaster do
    get '/', to: 'caster#show'
  end

  namespace :gi_album do
    get '/thumb/:size/:path', to: 'thumb#show', constraints: { path: /.*/ }
    get '/api/photo/index', to: 'photo#index'

    get '(*path)', to: 'ui#show', as: :ui
  end

end

app/controllers/svelte_test_controller.rb
# frozen_string_literal: true

class SvelteTestController < ::WebController

  protect_from_forgery with: :reset_session

  def hello
  end

  def post_select
    render :select
  end
end

app/views/svelte_test/hello.haml
= javascript_pack_tag 'hello_svelte'
-#= stylesheet_pack_tag 'hello_svelte'

.p-2
  %h1
    Hello

%hr
.p-2
  Svelte hello appears here
  .svelte-hello{ data: { msg: 'hello 1' } }

  and this is below it
  .svelte-hello{ data: { msg: 'hello 2' } }

app/views/svelte_test/select.haml
= javascript_pack_tag 'select_svelte'

.p-2
  %h1
    Select test

  = render partial: 'select_svelte_form', locals: { submit_url: select_svelte_test_index_path }

.fixed-bottom.border-top.bg-white
  .float-right
    .m-2.mr-3
      %a{ href: 'https://github.com/kikonen/select_svelte' }
        = image_tag('GitHub-Mark-32px.png', width: 16, height: !6)
        select_svelte

app/views/svelte_test/typeahead.haml
= javascript_pack_tag 'typeahead_svelte'

.p-2
  %h1
    Typeahead test

  = render partial: 'typeahead_svelte_form'

.fixed-bottom.border-top.bg-white
  .float-right
    .m-2.mr-3
      %a{ href: 'https://github.com/kikonen/typeahead_svelte' }
        = image_tag('GitHub-Mark-32px.png', width: 16, height: !6)
        typeahead_svelte